import { Card } from './card';

export const ALL_CARDS: Card[] = [
  new Card('Quiz', 'Pop Quiz'),
  new Card('Side', 'Bedside'),
  new Card('Love', 'Love Letter'),
  new Card('Mind', 'Mind Reader'),
  new Card('Tongue', 'Tongue-tied'),
  new Card('Skin', 'Snake Skin'),
  new Card('Hair', 'Bad Hair Day'),
  new Card('Split', 'Split Ends'),
  new Card('Talk', 'Talk Radio'),
  new Card('Ghost', 'Ghost Town'),
  new Card('Fence', 'Electric Fence'),
  new Card('Window', 'Window Shopping'),
  new Card('Taco', 'Taco Salad'),
  new Card('Wedding', 'Wedding Ring'),
  new Card('Tape', 'Tape Recorder'),
  new Card('Fall', 'Trust Fall'),
  new Card('Wife', 'Trophy Wife'),
  new Card('Toilet', 'Toilet Paper'),
  new Card('Sun', 'Sunburn'),
  new Card('Golf', 'Mini Golf'),
  new Card('Doughnut', 'Glazed Doughnut'),
  new Card('Toy', 'Toy Poodle'),
  new Card('Wash', 'Dishwasher'),
  new Card('Walk', 'Sleep Walking'),
  new Card('Empty', 'Empty Calories'),
  new Card('Email', 'Email Scam'),
  new Card('Frog', 'Leap Frog'),
  new Card('Family', 'Crime Family'),
  new Card('Spoon', 'Measuring Spoon'),
  new Card('Taste', 'Taste Buds'),
  new Card('Funeral', 'Funeral Home'),
  new Card('Gold', 'Gold Rush'),
  new Card('Whale', 'Beached Whale'),
  new Card('Bank', ' Bank Robber'),
  new Card('Newspaper', 'Newspaper Headline'),
  new Card('Sink', 'Sinkhole'),
  new Card('Refrigerator', 'Refrigerator Sale'),
  new Card('Tall', 'Tall Order'),
  new Card('Fry', 'French Fry'),
  new Card('Glove', 'Boxing Glove'),
  new Card('Blood', 'Blood Bank'),
  new Card('Fruit', 'Fruitcake'),
  new Card('Happy', 'Happy Hour'),
  new Card('Sweat', 'Cold Sweat'),
  new Card('Hat', 'Top Hat'),
  new Card('Suit', 'Bathing Suit'),
  new Card('Voice', 'Voicemail'),
  new Card('Teacher', 'Substitute Teacher'),
  new Card('Surgery', 'Plastic Surgery'),
  new Card('Handle', 'Handlebar'),
  new Card('Friend', 'Best Friend'),
  new Card('Elephant', 'Elephant Ear'),
  new Card('Question', 'Trick Question'),
  new Card('Grass', 'Grass Skirt'),
  new Card('Ladder', 'Rope Ladder'),
  new Card('Fact', 'Fact Finder'),
  new Card('Summer', 'Summer Vacation'),
  new Card('Dry', 'Dry Ice'),
  new Card('Driver', 'Backseat Driver'),
  new Card('Garage', 'Garage Band'),
  new Card('Hand', 'Handshake'),
  new Card('Stone', 'Stonehenge'),
  new Card('Green', 'Green Thumb'),
  new Card('Sleep', 'Sleeping Giant'),
  new Card('Globe', 'Snow Globe'),
  new Card('Water', 'White Water Rafting'),
  new Card('Fossil', 'Fossil Fuel'),
  new Card('Egg', 'Eggnog'),
  new Card('Stop', 'Truck Stop'),
  new Card('Glass', 'Champagne Glass'),
  new Card('Vegetable', 'Vegetable Garden'),
  new Card('Table', 'Ping Pong Table'),
  new Card('Vacation', 'Paid Vacation'),
  new Card('Wave', 'Tidal Wave'),
  new Card('Stool', 'Stool Pigeon'),
  new Card('Farm', 'Dairy Farm'),
  new Card('Foot', 'Big Foot'),
  new Card('Scarf', 'Wool Scarf'),
  new Card('Drive', 'Thumbdrive'),
  new Card('Sugar', 'Brown Sugar'),
  new Card('Syrup', 'Maple Syrup'),
  new Card('World', 'World Map'),
  new Card('Drum', 'Drumstick'),
  new Card('Sword', 'Sword Fight'),
  new Card('Fist', 'Fist Bump'),
  new Card('Gas', 'Gas Mask'),
  new Card('Dream', 'Dream Team'),
  new Card('Spill', 'Spilled Milk'),
  new Card('Finger', 'Fingernail Polish'),
  new Card('Sweater', 'Sweater Weather'),
  new Card('Silent', 'Silent Night'),
  new Card('Wall', 'Wall Street'),
  new Card('Easy', 'Speakeasy'),
  new Card('Double', 'Double Trouble'),
  new Card('Down', 'Rundown'),
  new Card('Fork', 'Fork Lift'),
  new Card('Earth', 'Mother Earth'),
  new Card('Tooth', 'Tooth Fairy'),
  new Card('Hamster', 'Hamster Wheel'),
  new Card('Class', 'Superclass'),
  new Card('Track', 'Tracksuit'),
  new Card('Five', 'High Five'),
  new Card('Short', 'Short Circuit'),
  new Card('Life', 'Life Sentence'),
  new Card('Ketchup', 'Ketchup Packet'),
  new Card('Train', 'Training Wheels'),
  new Card('Shoe', 'Shoelace'),
  new Card('Trap', 'Tourist Trap'),
  new Card('Skirt', 'Skirt Steak'),
  new Card('Kitchen', 'Kitchen Sink'),
  new Card('Trash', 'Trash Can'),
  new Card('Tree', 'Treehouse'),
  new Card('Hot', 'Hot Sauce'),
  new Card('Under', 'Under Pressure'),
  new Card('Trip', 'Road Trip'),
  new Card('Kill', 'Roadkill'),
  new Card('Turtle', 'Turtle Soup'),
  new Card('Lick', 'Salt Lick'),
  new Card('Lion', 'Lion Heart'),
  new Card('Zebra', 'Zebra Stripes'),
  new Card('Lip', 'Lipstick'),
  new Card('Spot', 'Sweet Spot'),
  new Card('Stomach', 'Stomach Cramp'),
  new Card('Storm', 'Thunderstorm'),
  new Card('Zoo', 'Petting Zoo'),
  new Card('Student', 'Student Driver'),
  new Card('Up', 'Upstairs'),
  new Card('Wolf', 'Werewolf'),
  new Card('Street', 'Street Sweeper'),
  new Card('Tutor', 'Math Tutor'),
  new Card('Hawk', 'Mohawk'),
  new Card('Team', 'Swim Team'),
  new Card('Heart', 'Broken Heart'),
  new Card('Gum', 'Gumball'),
  new Card('Head', 'Bonehead'),
  new Card('Smoke', 'Smoke Stack'),
  new Card('First', 'First Lady'),
  new Card('Army', 'Army Ant'),
  new Card('Shower', 'Cold Shower'),
  new Card('Hotel', 'Five Star Hotel'),
  new Card('House', 'Roughhouse'),
  new Card('Stamp', 'Stamp Collection'),
  new Card('Hungry', 'Power Hungry'),
  new Card('Hunt', 'Hunting Party'),
  new Card('Ice', 'Ice Cream Sandwich'),
  new Card('Snake', 'Rattlesnake'),
  new Card('Kick', 'Scissor Kick'),
  new Card('Shrimp', 'Jumbo Shrimp'),
  new Card('Socks', 'Loose Socks'),
  new Card('Wood', 'Wooden Teeth'),
  new Card('Succeed', 'Succeed As One'),
  new Card('Component', 'Component Map'),
  new Card('Cashback', 'Return Cashback'),
  new Card('Banner', 'Banner Carousel'),
  new Card('Drop', 'Drop Table'),
  new Card('Elastic', 'Elastic Compute Cloud'),
];
