import { Card } from './card';

export const ALL_CARDS: Card[] = [
  new Card('Quiz', 'Pop Quiz'),
  new Card('Side', 'Bedside'),
  new Card('Love', 'Love Letter'),
  new Card('Mind', 'Mind Reader'),
  new Card('Tongue', 'Tongue-tied'),
  new Card('Skin', 'Snake Skin'),
  new Card('Hair', 'Bad Hair Day'),
  new Card('Split', 'Split Ends'),
  new Card('Talk', 'Talk Radio'),
  new Card('Ghost', 'Ghost Town'),
  new Card('Fence', 'Electric Fence'),
  new Card('Window', 'Window Shopping'),
  new Card('Taco', 'Taco Salad'),
  new Card('Wedding', 'Wedding Ring'),
  new Card('Tape', 'Tape Recorder'),
  new Card('Fall', 'Trust Fall'),
  new Card('Wife', 'Trophy Wife'),
  new Card('Toilet', 'Toilet Paper'),
  new Card('Sun', 'Sunburn'),
  new Card('Golf', 'Mini Golf'),
  new Card('Doughnut', 'Glazed Doughnut'),
  new Card('Toy', 'Toy Poodle'),
  new Card('Wash', 'Dishwasher'),
  new Card('Walk', 'Sleep Walking'),
  new Card('Empty', 'Empty Calories'),
  new Card('Email', 'Email Scam'),
  new Card('Frog', 'Leap Frog'),
  new Card('Family', 'Crime Family'),
  new Card('Spoon', 'Measuring Spoon'),
  new Card('Taste', 'Taste Buds'),
  new Card('Funeral', 'Funeral Home'),
  new Card('Gold', 'Gold Rush'),
  new Card('Whale', 'Beached Whale'),
  new Card('Bank', ' Bank Robber'),
  new Card('Newspaper', 'Newspaper Headline'),
  new Card('Sink', 'Sinkhole'),
  new Card('Refrigerator', 'Refrigerator Sale'),
  new Card('Tall', 'Tall Order'),
  new Card('Fry', 'French Fry'),
  new Card('Glove', 'Boxing Glove'),
  new Card('Blood', 'Blood Bank'),
  new Card('Fruit', 'Fruitcake'),
  new Card('Happy', 'Happy Hour'),
  new Card('Sweat', 'Cold Sweat'),
  new Card('Hat', 'Top Hat'),
  new Card('Suit', 'Bathing Suit'),
  new Card('Voice', 'Voicemail'),
  new Card('Teacher', 'Substitute Teacher'),
  new Card('Surgery', 'Plastic Surgery'),
  new Card('Handle', 'Handlebar'),
];
